name: kernel-images

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  kernel-default:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to INFN Container Registry
        uses: docker/login-action@v1
        with:
          registry: harbor.cloud.infn.it
          username: ${{ secrets.harbor_user }}
          password: ${{ secrets.harbor_clisecret }}

      - name: Get Repo Owner
        id: get_repo_owner
        run: echo ::set-output name=repo_owner::$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')

      - name: Build container kernel-default
        uses: docker/build-push-action@v2
        with:
          context: ./kernels/default
          outputs: "type=registry,push=true"
          tags: |
            harbor.cloud.infn.it/unpacked/BETIF_DIFAET/kernel-default:${{ env.RELEASE_VERSION }}
          file: ./kernels/default/Dockerfile
          platforms: linux/amd64
